### ISSUE TITLE
On going stream-

### ISSUE THREAD

**Issue by Pyzza28** [niseyami/twitcasting-dl#1]
Hello there, Thank you so much for posting this, I have some few questions about it.

Is this still effective as of today? (Because I read a comment in your youtube video that said it no longer works, the comment was posted about two weeks ago)

Does this method work for an on-going live stream?

Again, thanks so much

**Comment by kubisch** [comment]
Hello,

Sorry for the late reply, the method I have detailed on the GitHub still works, but the method in the comment does not.
I hope that clears up the confusion


________________________________
