### ISSUE TITLE
HTTP error 502 Bad Gateway

### ISSUE THREAD

**Issue by yukarina** [niseyami/twitcasting-dl#10]
Hello, I have followed your instructions on downloading, and it seems that on some of the videos, there's a tendency to receive that "HTTP error 502 Bad Gateway" error, and a good chunk of the video will not be downloaded.

Do you have any advice for "HTTP error 502 Bad Gateway"?

I have attached a screenshot of the issue below.
![unknown](https://user-images.githubusercontent.com/83133334/115966722-6fbcff80-a561-11eb-847d-e4647f65dc68.png)

**Comment by i-cant-git** [comment]
I have the same problem.
I tried adding `-cookies` and changed `Origin` header but it didn't work, still get 502.

**Comment by kubisch** [comment]
Hey, can you please get into contact with me on discord (Cubic#8929).
I personally haven't see this occur and can't replicate it so I'd need a little bit more information to find a fix.

**Comment by yukarina** [comment]
Alright, will send you a friend request on Discord.

**Comment by plase0** [comment]
hello, i have the same problem
Is there a solution to this problem?

**Comment by alcoholoni** [comment]
im having the same problem, any fix?

**Comment by kuonyuu** [comment]
same problem too
dl first video only
