### ISSUE TITLE
spm is not recognized

### ISSUE THREAD

**Issue by holopekochan** [niseyami/twitcasting-dl#18]
I followed the README and tried to download a VOD but it has an error saying "At least one output file must be specified" and
'spm' is not recognized

ffmpeg.exe -protocol_whitelist file,http,https,tcp,tls,crypto -user_agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36" -headers "Origin: https://twitcasting.tv" -i https://dl193248.twitcasting.tv/tc.vod.v2/v1/streams/715540043.0.2/hls/master.m3u8?k=%2Ftc.vod%2Fv%2F715540043.0.2-1648074005-1648102805-ec0fa93b-76db3eb39df6dc35&spm=1 -c copy test.mkv

Any help would be appericated

![ffmpeg](https://user-images.githubusercontent.com/12294117/159806502-f484bc65-a03d-4ceb-9f0d-1ab456949d91.PNG)

**Comment by Chymion** [comment]
You have to remove &spm=1 at the end of the video link.
