### ISSUE TITLE
"At least one output file must be specified"

### ISSUE THREAD

**Issue by YuzuAi** [niseyami/twitcasting-dl#19]
I tried to download a VOD but it has this error "At least one output file must be specified" and also says ""-c" is not recognized as an internal or external command, program or executable batch file."

I don't know if I messed something up, so here is the code I used, thanks in advance
 
ffmpeg.exe -protocol_whitelist file,http,https,tcp,tls,crypto -user_agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.62 Safari/537.36" -headers "Origin: https://twitcasting.tv" -i https://dl193235.twitcasting.tv/tc.vod.v2/v1/streams/733307533.0.2/hls/master.m3u8?k=%2Ftc.vod%2Fv%2F733307533.0.2-1653982546-1654011346-a1c26c87-904d5172ad68e2e1& -c copy haruno.mkv
![Captura](https://user-images.githubusercontent.com/106582393/171123510-139ad6a0-8ecc-4c50-bf92-09271a5da07e.PNG)

**Comment by alcoholoni** [comment]
having the same problem too, did u manage to find any fix?
