### ISSUE TITLE
This method outputs corrupted audio, getting "Non-monotonous DTS in output stream 0:1;"

### ISSUE THREAD

**Issue by xanek** [niseyami/twitcasting-dl#5]
```
[matroska @ 000001f31ec62680] Non-monotonous DTS in output stream 0:1; previous: 2736876, current: 2736769; changing to 2736876. This may result in incorrect timestamps in the output file.
[matroska @ 000001f31ec62680] Non-monotonous DTS in output stream 0:1; previous: 2736876, current: 2736790; changing to 2736876. This may result in incorrect timestamps in the output file.
[matroska @ 000001f31ec62680] Non-monotonous DTS in output stream 0:1; previous: 2736876, current: 2736812; changing to 2736876. This may result in incorrect timestamps in the output file.
```
I have always been getting this when trying to download through twitcast through this method. I last opened a issue in **OCTOBER of last year** in regards to this but it was never answered so I am making a new one in the hopes that it gets noticed.

The audio from this method is corrupted / is not playable, even after converting from mkv to mp4, the audio is either missing or has random bits that come up that are all corrupted.

**Comment by kubisch** [comment]
Hey, I don't actually use twitcasting myself that much, and I don't exactly remember the intricacies of ffmpeg.

But, send me a dm on discord (Cubic#3792) and I'll try to help you. If I remember correctly though, the only reason this happened was because of trying to save it as a mp4 initially, which is why I recommended downloading it as an mkv first.

**Comment by xanek** [comment]
Okay, I will contact you via discord DM

**Comment by kubisch** [comment]
Closed, since issue was caused by outdated ffmpeg version (4.2) which presumably had a bug that has since been fixed.
This issue should not occur in higher versions.
Please check you are use the newest ffmpeg version before reporting an issue.
