### ISSUE TITLE
Can you help me for the twitcasting post pls

### ISSUE THREAD

**Issue by Mofuchan** [niseyami/twitcasting-dl#7]
Hello
I'm trying to download a live from twitcasting but I don't really understand what you mean when you said to past the code the thing is that I don't know where to past it, can you specify where to or maybe trying to explain me 
Thanks 

(i'm french sorry if I make mistake)

**Comment by kubisch** [comment]
if you mean this code:

`let a=[];for(let _ of JSON.parse(document.querySelector("video")["dataset"]["moviePlaylist"])[2])a.push(_.source?.url);console.log(a.join("\n"))`

Then, all you have to do on the twitcasting webpage is press "CTRL+ SHIFT + J" (on windows/chrome). A box will open up on the side and you just paste the code in there and press enter. Let me know if you have any more issues.

**Comment by kubisch** [comment]
Oh please note, this won't work on a live broadcast, only VODs. I'm not quite sure how to save something that's live on twitcasting, although I might look into that.

**Comment by Mofuchan** [comment]
OK thank you

**Comment by kubisch** [comment]
Do you have anything else to ask? If you don't then I'll close this issue (you can always make a new one in the future).

**Comment by bb850878** [comment]
@niseyami Hello!
I'm not sure if it's polite or not to comment in the "Issues".
I'm a GitHub beginner,please forgive me if I’ve offended you.
I want to ask is there any method to download the live on twitcasting?
Some live on twitcasting have no archive,so I want to download them when it's streaming.
Also,your method which tells me how to find .m3u8 file helps a lot,thanks!
