### ISSUE TITLE
 HTTP error 502 Bad Gateway

### ISSUE THREAD

**Issue by tanukisses** [niseyami/twitcasting-dl#9]
While this has previously worked in the past, every time i copy the .m3u8 link for any video, it gives me this error
[https @ 000002ac401bf700] HTTP error 502 Bad Gateway
https://dl101.twitcasting.tv/tc.vod/v/673461392.0.2-1618378138-1618406938-9c3c2378-30fb14de253952d9/fmp4/index.m3u8: Server returned 5XX Server Error reply

All the other code works fine, so has Twitcast changed the links so this doesn't work anymore? Should I be entering the link in a different format?

Thank you!

**Comment by kubisch** [comment]
Hey, sorry for the late response. What you guessed is right, twitcasting has changed it so that the links are uniquely generated for each new connection, and can only be used by that connection. I'm working on a solution but it will be a bit more involved so it'll take a while.

**Comment by kubisch** [comment]
@tanukisses Hey again, I've released an update to the document that should fix this issue. Please give it a read.
